import os
import time
import argparse
import boto3
from botocore.exceptions import ClientError

REGION = "eu-west-2"
AMI_ID = "ami-0b9932f4918a00c4f" #hardcoded this, not ideal but it is what it is for now, will need to be updated if we want to use a different region or a different base image.
INSTANCE_TYPE = "t3.micro"
CONFIG_FILE_PATH = "instance_config.txt"

INSTANCE_TAGS = [
    {"Key": "Name", "Value": "Automated-Dev-Box"},
    {"Key": "Environment", "Value": "Development"},
    {"Key": "ManagedBy", "Value": "Boto3-Script"}
]

def provision_ec2(key_name):
    ec2 = boto3.resource('ec2', region_name=REGION)
    print(f"🚀 Starting EC2 provisioning in {REGION} using key pair '{key_name}'...")
    
    try:
        instances = ec2.create_instances(
            ImageId=AMI_ID,
            MinCount=1,
            MaxCount=1,
            InstanceType=INSTANCE_TYPE,
            KeyName=key_name,  # Passed dynamically from CLI
            TagSpecifications=[{'ResourceType': 'instance', 'Tags': INSTANCE_TAGS}]
        )
        
        instance = instances[0]
        print(f"⏳ Instance created with ID: {instance.id}. Waiting for it to enter 'running' state...")
        
        instance.wait_until_running()
        instance.reload()
        public_ip = instance.public_ip_address
        
        if not public_ip:
            print("⚠️ Instance is running, but no Public IP was assigned.")
            return
            
        print(f"✅ Instance is running! Public IP: {public_ip}")
        write_to_config(instance.id, public_ip)
        
    except ClientError as e:
        print(f"❌ An AWS client error occurred: {e}")

def write_to_config(instance_id, ip_address):
    try:
        with open(CONFIG_FILE_PATH, "w") as config_file:
            config_file.write("# Generated by Auto-Provisioning Script\n")
            config_file.write(f"INSTANCE_ID={instance_id}\n")
            config_file.write(f"PUBLIC_IP={ip_address}\n")
        print(f"💾 Configuration written to: {os.path.abspath(CONFIG_FILE_PATH)}")
    except IOError as e:
        print(f"❌ Failed to write config file: {e}")

if __name__ == "__main__":
    # Set up argument parsing 
    parser = argparse.ArgumentParser(description="Auto-provision an AWS EC2 instance.")
    parser.add_argument(
        "--key-name", 
        required=True, 
        help="The name of the AWS EC2 Key Pair to associate with the instance."
    )
    
    args = parser.parse_args()
    provision_ec2(args.key_name)